### ISSUE TITLE
ReSharper and TaskObserve Extension versioning

### ISSUE THREAD

**Issue by square-unit** [0xorial/ForceTaskObserve#1]
Hi All,

I'm support engineer of ReSharper team. The latest TaskObserve Extension for ReSharper 1.1.0 breaks R# being installed into R# 2017.3.x

The supported R# versions for the version weren't specified properly. It is declared as compatible with all the newer versions above R# Wave 2017.1 (≥ 8.0.0). So it was available in R# Extension Manager despite it wasn't tested with more recent versions and can break the R# installation.

We removed the version from the ReSharper Gallery. Please fix the versioning issue and upload the updated version with properly specified supported R# versions. It will become available in the Extension Manager of all the compatible R# builds.

--
Andrey Simukov
Support Engineer
JetBrains
http://www.jetbrains.com
The Drive To Develop
andrey.simukov@jetbrains.com

**Comment by Mike-E-angelo** [comment]
I just went through THREE FULL PAGES of ReSharper extensions to upgrade to 2018.1, and this was the only extension that wasn't available.  SHAME!!!  SHAMMMMMMMMMMEEEEEEEEEE11111 😆

**Comment by 0xorial** [comment]
@square-unit , TBH I am a bit confused with versioning... I found [this](https://www.jetbrains.com/help/resharper/sdk/Extensions/PlatformVersioning.html), but it only has versions until 2017.2. Is there any place where I can find some more details?

**Comment by square-unit** [comment]
@0xorial please refer to https://github.com/JetBrains/resharper-devguide/blob/master/Extensions/PlatformVersioning.md

**Comment by 4ux-nbIx** [comment]
Would be awesome to get this extension back in R# Gallery! 
By the way, I've updated ReSharper SDK references, compiled and installed it manually today and it works! No changes required to support the latest R# version.

**Comment by 0xorial** [comment]
Rejoice! Extension is back in the gallery.

**Comment by Mike-E-angelo** [comment]
Woohoo!  Thank you @0xorial !!! 🎉
